# Generated by Django 4.0.4 on 2024-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
        ('users', '0003_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='orders',
            field=models.ManyToManyField(blank=True, to='products.checkout'),
        ),
    ]
