# Generated by Django 4.0.4 on 2024-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
