# Generated by Django 4.0.4 on 2024-07-26 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_prescription_email_prescription_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
