# Generated by Django 4.0.4 on 2024-07-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_prescription_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
    ]
