# Generated by Django 4.0.4 on 2024-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_prescription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions'),
        ),
    ]
