# Generated by Django 4.0.4 on 2024-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_prescription_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(default=1, upload_to='prescriptions'),
            preserve_default=False,
        ),
    ]
