# Generated by Django 4.0.4 on 2024-07-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_prescription_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture_url',
        ),
    ]
