# Generated by Django 4.0.4 on 2024-07-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(upload_to='prescriptions/'),
        ),
    ]
