# Generated by Django 4.0.4 on 2024-07-28 21:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_prescription_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='document'),
            preserve_default=False,
        ),
    ]
