# Generated by Django 4.0.4 on 2024-07-29 10:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_prescription_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions', validators=[users.models.validate_file_size]),
        ),
    ]
