# Generated by Django 4.0.4 on 2024-07-29 17:00

import cloudinary_storage.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_prescription_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='document',
            field=models.FileField(default=1, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='', validators=[users.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
