services:
  - type: web
    name: PharmMams
    env: python
    buildCommand: "pip install -r requirements.txt && 
    python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn PharmMams.wsgi:application"
