# Generated by Django 4.0.4 on 2024-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='thumbnail-placeholder-500x334.jpg', upload_to='product_images'),
        ),
    ]
