# Generated by Django 4.0.4 on 2024-07-22 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆ (1/5)'), (2, '★★☆☆☆ (2/5)'), (3, '★★★☆☆ (3/5)'), (4, '★★★★☆ (4/5)'), (5, '★★★★★ (5/5)')], null=True)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
