# Generated by Django 4.0.4 on 2024-07-29 17:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='thumbnail-placeholder-500x334.jpg', max_length=255, verbose_name='image'),
        ),
    ]
